baseURL: "https://glistening-kheer-159f89.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "MEGA-ACE UNAM"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "MEGA-ACE UNAM"
  description: "Nuestro objetivo es transformar el panorama de la blockchain."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://www.instagram.com/unam_mx/"
    facebook: "https://www.facebook.com/UNAM.MX.Oficial/"
    twitter: "https://twitter.com/UNAM_MX"

  location:
    - "Facultad de Ingeniería, Av. Universidad 3000, Ciudad Universitaria, Coyoacán, Cd. Mx., CP 04510"

  contact:
    - "algorand@unam.mx"
    - "55 0000 0000"

  copyright: "Copyright © 2023. Departamento de Computación / DIE / Facultad de Ingeniería / UNAM. Todos los Derechos Reservados."

  postProcess: false

menus:
  main:
    - name: "Sobre nosotros"
      url: "/sobre_nosotros"
      weight: 1

    - name: "Investigación"
      url: "/investigacion"
      weight: 2
      
    - name: "Noticias/Artículos"
      url: "/noticias-articulos"
      weight: 3

    - name: "Nuestro equipo"
      url: "/equipo"
      weight: 4

    - name: "Eventos"
      url: "/eventos"
      weight: 5

    - name: "Cursos"
      url: "/cursos"
      weight: 6

  buttons:
    - name: "Contacto"
      url: "/contacto"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Sobre nosotros"
      url: "/sobre_nosotros"
      weight: 1

    - name: "Investigación"
      url: "/investigacion"
      weight: 2
    
    - name: "Noticias/Artículos"
      url: "/noticias-articulos"
      weight: 3

    - name: "Nuestro equipo"
      url: "/equipo"
      weight: 4

    - name: "Eventos"
      url: "/eventos"
      weight: 5

    - name: "Cursos"
      url: "/cursos"
      weight: 6
